### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Hiswe** [Hiswe/dumb-account#1]
- [ ] Enhance quotation form
  - [ ] make use of [redux-form](http://redux-form.com/6.0.5/)
    - [ ] use `combineReducer`
      - [ ] remove immutable.js — I find it heavy to use
        - [ ] disable quotations
        - [ ] separate customers-home &  customers create form — make a new edit
        - [ ] replace immutable by [seamless-immutable](https://github.com/rtfeldman/seamless-immutable) 
        - [ ] migrate quotations
